services:
  gqlserver:
    image: relatedcode/gqlserver:latest
    container_name: gqlserver
    ports:
      - "4000:4000"
    environment:
      DB_HOST: pg
      DB_PORT: 5432
      DB_DATABASE: gqlserver
      DB_USER: gqlserver
      DB_PASSWORD: gqlserver

      CACHE_HOST: rd
      CACHE_PORT: 6379
      CACHE_PASSWORD: gqlserver
      
      MINIO_ROOT_USER: gqlserver
      MINIO_ROOT_PASSWORD: gqlserver

      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: gqlserver

      SECRET_KEY: f2e85774-9a3b-46a5-8170-b40a05ead6ef

    depends_on:
      - redis
      - postgres
    command:
      [
        "./wait-for-it.sh",
        "pg:5432",
        "--",
        "./wait-for-it.sh",
        "rd:6379",
        "--",
        "npm",
        "run",
        "watch:config"
      ]
    volumes:
      - ./config:/app/config
  
  gqlserver_admin:
    image: relatedcode/gqlserver-admin:latest
    container_name: gqlserver_admin
    ports:
      - "80:3000"
    depends_on:
      - gqlserver

  postgres:
    container_name: pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gqlserver
      POSTGRES_PASSWORD: gqlserver
      POSTGRES_DB: gqlserver
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: rd
    ports:
      - "6379:6379"
    command: redis-server --requirepass gqlserver --save 60 1
    volumes:
      - ./data/rd:/data
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: gqlserver
      MINIO_ROOT_PASSWORD: gqlserver
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
